apiVersion: v1
kind: Secret
metadata:
  name: "secret-{{.Release.Name}}"
  namespace: "{{.Values.deploy.namespace}}"
type: Opaque
stringData:
    PASSWORD_RABBIT: "{{.Values.secrets.password_rabbit}}"
    PASSWORD_RABBIT_ELK: "{{.Values.secrets.password_rabbit_elk}}"
    PASSWORD_IBMMQ: "{{.Values.secrets.password_ibmmq}}"
